  version: "3"

  networks:
   inception:
     driver: bridge 

  services:
    nginx:
      container_name: nginx
      image: nginx
      volumes:
        - wp:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "443:443"
      restart: always

    wordpress:
      container_name: wordpress
      env_file: .env
      image: wordpress
      volumes:
        - wp:/var/www/html
      networks:
        - inception
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      depends_on:
        - mariadb
      restart: always
      expose:
        - "9000"

    mariadb:
      container_name: mariadb
      networks:
        - inception
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      image: mariadb
      env_file: .env
      volumes:
        - db:/var/lib/mysql
      restart: always
      expose:
        - "3306"

  volumes:
    wp:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/wp
    db:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/db


